# RPICAN Protocol Parser Configuration
# This file configures which parsers to use for different CAN message IDs

# Default parser for unknown messages
default_parser: "Raw Data v1.0"

# Parser configurations
parsers:
  # Built-in raw data parser (fallback)
  - name: "Raw Data v1.0"
    enabled: true
    priority: 10  # Lowest priority (fallback)
    config: {}
  
  # Golf cart brake sensor parser
  - name: "Golf Cart Brake Sensor v1.0"
    enabled: true
    priority: 2
    config: {}
  
  # Golf cart throttle sensor parser  
  - name: "Golf Cart Throttle Sensor v1.0"
    enabled: true
    priority: 2
    config: {}
  
  # STM32F103 wiring harness parser
  - name: "STM32F103 Wiring Harness v1.0"
    enabled: true
    priority: 1  # Highest priority for hardware-specific messages
    config: {}

# CAN ID to parser mappings
can_id_mappings:
  # Direct ID mappings (specific CAN IDs)
  direct:
    # Golf cart sensors
    "0x100": "Golf Cart Brake Sensor v1.0"
    "0x101": "Golf Cart Throttle Sensor v1.0"
    
    # STM32F103 wiring harness
    "0x410": "STM32F103 Wiring Harness v1.0"
  
  # Range mappings (CAN ID ranges)
  ranges:
    # Example: OBD-II diagnostic range
    - start: "0x7E0"
      end: "0x7E7"
      parser: "Raw Data v1.0"  # No OBD-II parser yet
    
    # Example: J1939 range  
    - start: "0x0CF00000"
      end: "0x0CFFFFFF"
      parser: "Raw Data v1.0"  # No J1939 parser yet

# Parser-specific settings
parser_settings:
  # Settings for wiring harness parser
  wiring_harness:
    validate_sequence: true
    validate_crc: true
    validate_end_marker: true
    
  # Settings for golf cart parsers
  golf_cart:
    validate_sensor_ids: true
    
# Display settings
display:
  # Default view mode
  default_view: "compact"  # compact or detailed
  
  # Auto-switch to detailed view for specific parsers
  auto_detailed:
    - "STM32F103 Wiring Harness v1.0"
    
  # Color scheme
  colors:
    valid: "green"
    warning: "yellow"
    error: "red"
    unknown: "dim"